import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Maliek News App</title>
        <link rel="icon" href="/favicon.ico" />
          <script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
    <script>
      window.googletag = window.googletag || {cmd: []};

      googletag.cmd.push(function() {
        // Declare slots initially present on the page
        googletag.defineSlot('/6355419/Travel', [728, 90], 'leaderboard')
            .setTargeting("test","infinitescroll")
            .addService(googletag.pubads());

        // Enable SRA to honor competetive exclusions and roadblocks.
        googletag.pubads().enableSingleRequest();

        // Enable services
        googletag.enableServices();
      });

      // Function to add content to page
      function moreContent() {
        // Define the slot itself, register it and fetch an ad.
        googletag.cmd.push(function() {
          var slot = googletag.defineSlot('/6355419/Travel', [728, 90])
              .setTargeting('test', 'infinitescroll')
              .addService(googletag.pubads());

          var div = document.createElement('div');
          div.id = slot.getSlotElementId(); // auto-generated by GPT
          document.body.appendChild(div);

          // Call display() to register the slot as ready and fetch an ad.
          googletag.display(slot);
        });
      }
    </script>

      </Head>

      <main>
        <Header title="Welcome to Maliek News" />
        <p className="description">
          Get started by editing <code>pages/index.js</code>
        </p>
      <div id="page-content" style="height: 900vh;">
      <h1 id="status">Tags Or Pixels</h1>
      <div id="static-ad-1" style="width: 100px; height: 100px;"></div>
    </div>
    <script>
        googletag.cmd.push(function() {
          // Ensure the first call to display comes after static ad slot
          // divs are defined.
          googletag.display(staticSlot);
        });
      </script>

      </main>

      <Footer />
    </div>
  )
}
